config/routes.rb
Rekk::Application.routes.draw do

  resources :work_orders, except: [:edit]
  resources :comments
  resources :billing_addresses, only: [:create]
  resources :home, only: [:index]
  resources :users, only: [:index, :show, :destroy]
  resources :clients
  resources :products do
    collection do
      get :picker
    end
  end
  resources :product_types, except: [:destroy, :edit]
  resources :roles
  resources :contacts, only: [:index, :show]
  resources :work_order_products
  get '/login', to: 'home#login', as: :login
  get   '/logout', to: 'sessions#logout'

  match '/auth/:provider/callback', to: 'sessions#create'
  match '/auth/failure', to: 'sessions#failure' 

  root :to => 'home#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment
  attr_accessible :commentable, :commentable_id, :user, :title, :comment
  belongs_to :commentable, :polymorphic => true

  default_scope :order => 'created_at DESC'

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_filter :find_commentable, only: [:index, :new, :create, :update]

  # GET /comments
  # GET /comments.json
  def index
    @comments = @commentable.comments.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @users }
    end
  end

  # GET /comments/#id/edit
  # GET /comments/#id/edit.json

  def edit
    @comment = Comment.find(params[:id])
    respond_to do |format|
      format.html { render action: "new", layout: false }
      format.json { render json: @comment }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  # requires that params contans commentable and commentable_id
  def new
    @comment = Comment.new(options_for_commentable)
    respond_to do |format|
      format.html { render layout: false } # new.html.erb
      format.json { render json: @users }
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @comment.destroy()
    render nothing: true
  end

  # GET /comments/1
  # GET /comments/1.json
  def create
    @comment = Comment.find_or_initialize_by_id(params[:id])
    params[:comment][:user] = current_user
    @comment.update_attributes(params[:comment])

    if @comment.save
      respond_to do |format|
        format.html { render action: "show", layout: false }
        format.json { render json: @comment }
      end
    else
      respond_to do |format|
        format.html { render action: "new", layout: false }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    create
  end

  private

  def find_commentable
    @commentable = Comment.find_commentable(params[:type] || params[:comment][:commentable],
                                            params[:commentable_id] || params[:comment][:commentable_id])
    instantiate_commentable_param
  end

  def instantiate_commentable_param
    if params[:comment] && params[:comment][:commentable]
      params[:comment][:commentable] = @commentable
    end
  end

  def options_for_commentable
    { commentable: @commentable,
      commentable_id: @commentable.id, 
      user: current_user }
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_form.html.erb
<div class="modal" id="comment_modal">
  <%= form_for @comment, remote: true do |f| %>
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <b><%= t :work_order_comment %></b><span> - </span><span><%= @comment.user.name %></span>
    </div>
    <div class="modal-body">
      <%= f.hidden_field :commentable, value: @comment.commentable.class %>
      <%= f.hidden_field :commentable_id, value: @comment.commentable.id %>
      <div class="control-group">
        <label class="control-label" for="title">
          <%= t :title, scope: [:activerecord, :models, :comment] %>
        </label>
        <%= f.text_field :title, class: "fixed-modal-input-width" %>
      </div>
      <div class="control-group">
        <label class="control-label" for="title">
          <%= t :comment, scope: [:activerecord, :models, :comment] %>
        </label>

        <%= f.text_area :comment, rows: 10, class: "fixed-modal-input-width" %>
      </div>
    </div>
    <div class="modal-footer">
      <a href="#" class="btn" data-dismiss="modal"><%= t :cancel %></a>
      <button type="submit" class="btn btn-primary"><%= t :save %></button>
    </div>
  <% end %>
</div>

app/views/comments/_li.html.erb
<% comment = @comment unless comment %>
<li class="comment" id="comment_<%= comment.id %>">
<div>
  <span><%= comment.created_at.strftime("%Y-%m-%d %H:%M") %></span>
  <b><%= comment.user.name if comment.user %></b>
  <span>: <%= comment.title %></span>
  <span class="pull-right">
    <% if comment.user == @current_user %>
      <%= link_to t(:delete), comment_path(comment), method: :delete, remote: true, class: 'delete-comment' %>
      <%= link_to t(:edit), edit_comment_path(comment), remote: true, class: 'edit-comment' %>
    <% end %>
  </span>
</div>
<pre><%= comment.comment %></pre>
</li>

app/views/comments/index.html.erb
<%= javascript_include_tag "work_orders" %>
<ul>
<% @comments.each do |comment| %>
  <%= render 'li', comment: comment %>
<% end %>
</ul>

app/views/comments/show.html.erb
<%= render partial: 'li', comment: @comment %>