config/routes.rb
Rekk::Application.routes.draw do

  resources :work_orders, except: [:edit]
  resources :comments
  resources :billing_addresses, only: [:create]
  resources :home, only: [:index]
  resources :users, only: [:index, :show, :destroy]
  resources :clients
  resources :products do
    collection do
      get :picker
    end
  end
  resources :product_types, except: [:destroy, :edit]
  resources :roles
  resources :contacts, only: [:index, :show]
  resources :work_order_products
  get '/login', to: 'home#login', as: :login
  get   '/logout', to: 'sessions#logout'

  match '/auth/:provider/callback', to: 'sessions#create'
  match '/auth/failure', to: 'sessions#failure' 

  root :to => 'home#index'

end

app/models/client.rb
class Client < ActiveRecord::Base
  #relations
  has_many :contacts, inverse_of: :client, dependent: :destroy
  has_many :work_orders, inverse_of: :client
  belongs_to :user, inverse_of: :clients
  has_many :billing_addresses, inverse_of: :client, dependent: :destroy
  #
  # attribute whitelist
  attr_accessible :name, 
                  :local_name, 
                  :accounting_code, 
                  :contacts_attributes,
                  :memo,
                  :user_id,
                  :billing_addresses_attributes

  accepts_nested_attributes_for :contacts, 
    allow_destroy: true, 
    reject_if: proc  { |attributes| 
      attributes[:name].blank? || attributes[:email].blank?
    }
  
  accepts_nested_attributes_for :billing_addresses,
    allow_destroy: true,
    reject_if: proc { |attributes|
      attributes[:postal_code].blank? || attributes[:address_1].blank?
    }

  validates_presence_of :user, :name
  validates_uniqueness_of :name

  def self.by_user(user)
    where(user_id:  user.id)
  end


end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  protect_from_forgery
  before_filter :clients_list, only: [:show, :new, :index]

  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clients }
    end
  end

  def create
    client = Client.new(params['client'])
    client.save!
    redirect_to clients_path
  end 

  def show
    respond_to do |format|
      @client = Client.includes(:contacts, :billing_addresses).find(params[:id])
      format.html
      format.json { render json: @client.to_json( include: [:contacts, :billing_addresses] ) }
    end
  end 

  def new
    @client = Client.new(:user_id => current_user.id)
  end

  def update
    client = Client.find(params[:id])
    client.update_attributes(params[:client])
    flash[:sucess] = "woot!"
    redirect_to client_path(client)
  end

  def destroy
    client = Client.find(params[:id])
    client.destroy
    redirect_to clients_path
  end

  private
  def clients_list
    @clients = params[:alternate] ? Client.all : Client.by_user(current_user) 
  end


end

app/views/clients/_add_billing_address.html.erb
<div id="add_billing_address_form" class="modal hide fade" style="display:none;">
  <div class="modal-header"><%=t :add_billing_address%> </div>
  <div class="modal-body">
    <form class="form-horizontal">
      <fieldset>
        <div class="control-group">
          <label class="control-label">
            <%=t :postal_code, scope: [:activerecord, :models, :billing_address] %>
          </label>
          <div class="controls">
            <%= text_field_tag(:postal_code, '', class: "input-medium", required: true) %>
            <span class="help-inline"></span>
          </div>
        </div>
        <div class="control-group">
          <label class="control-label">
            <%=t :address_1, scope: [:activerecord, :models, :billing_address] %>
          </label>
          <div class="controls">
            <%= text_field_tag(:address_1, '', class: "input-xlarge", required: true) %>
            <span class="help-inline"></span>
          </div>
          
        </div>

<div class="control-group">
          <label class="control-label">
            <%=t :address_2, scope: [:activerecord, :models, :billing_address] %>
          </label>
          <div class="controls">
            <%= text_field_tag(:address_2, '', class: "input-xlarge") %>
            <span class="help-inline"></span>
          </div>
          
        </div>
<div class="control-group">
          <label class="control-label">
            <%=t :address_3, scope: [:activerecord, :models, :billing_address] %>
          </label>
          <div class="controls">
            <%= text_field_tag(:address_3, '', class: "input-xlarge") %>
            <span class="help-inline"></span>
          </div>
          
        </div>


        <div class="control-group">
          <label class="control-label">
            <%=t :company_name, scope: [:activerecord, :models, :billing_address] %>
          </label>
          <div class="controls">
            <%= email_field_tag(:company_name, '', class: "input-xlarge", required: true) %>
            <span class="help-inline"></span>
          </div>
        </div>

        <div class="control-group">
          <label class="control-label">
            <%=t :recipient_name, scope: [:activerecord, :models, :billing_address] %>
          </label>
          <div class="controls">
            <%= text_field_tag(:recipient_name, '', class: "input-xlarge", required: true) %>
            <span class="help-inline"></span>
          </div>
        </div>

        <div class="control-group">
          <label class="control-label">
            <%=t :recipient_title, scope: [:activerecord, :models, :billing_address] %>
          </label>
          <div class="controls">
            <%= text_field_tag(:recipient_title, '', class: "input-xlarge") %>
            <span class="help-inline"></span>
          </div>
        </div>
      </fieldset>
    </form>
    <hr>
    <div class="modal-footer">
      <button id="btn_save" class="btn btn-primary"><%=t :save%></button>
      <button id="btn_cancel" class="btn"><%=t :cancel%></button>
    </div>
  </div>
</div>

app/views/clients/_add_contact.html.erb
<div id="add_contact_form" class="modal hide fade" style="display:none;">
  <div class="modal-header"><%=t :add_contact%> </div>
  <div class="modal-body">
    <form class="form-horizontal">
      <fieldset>
        <div class="control-group">
          <label class="control-label">
            <%=t :name, scope: [:activerecord, :models, :contact] %>
          </label>
          <div class="controls">
            <%= text_field_tag(:name, '', class: "input-xlarge", required: true) %>
            <span class="help-inline"></span>
          </div>
        </div>
        <div class="control-group">
          <label class="control-label">
            <%=t :job_title, scope: [:activerecord, :models, :contact] %>
          </label>
          <div class="controls">
            <%= text_field_tag(:job_title, '', class: "input-xlarge", required: true) %>
            <span class="help-inline"></span>
          </div>
        </div>

        <div class="control-group">
          <label class="control-label">
            <%=t :email, scope: [:activerecord, :models, :contact] %>
          </label>
          <div class="controls">
            <%= email_field_tag(:email, '', class: "input-xlarge", required: true) %>
            <span class="help-inline"></span>
          </div>
        </div>

        <div class="control-group">
          <label class="control-label">
            <%=t :phone, scope: [:activerecord, :models, :contact] %>
          </label>
          <div class="controls">
            <%= telephone_field_tag(:phone, '', class: "input-xlarge", required: true) %>
            <span class="help-inline"></span>
          </div>
        </div>

        <div class="control-group">
          <label class="control-label">
            <%=t :division, scope: [:activerecord, :models, :contact] %>
          </label>
          <div class="controls">
            <%= text_field_tag(:division, '', class: "input-xlarge", required: true) %>
            <span class="help-inline"></span>
          </div>
        </div>
      </fieldset>
    </form>
    <hr>
    <div class="modal-footer">
      <button id="btn_save" class="btn btn-primary"><%=t :save%></button>
      <button id="btn_cancel" class="btn"><%=t :cancel%></button>
    </div>
  </div>
</div>

app/views/clients/_form.html.erb
<%= form_for @client, :html => { class: 'form-horizontal' } do |f| %>
  <% unless @client.new_record? %> 
    <% if @client.user %>
      <%= gravatar_for @client.user.email, size: 48, style: 'position:absolute;' %>
    <% end %>
    <%=link_to(client_path(@client), method: :delete, confirm: I18n.t(:confirm_delete_client), class: 'btn btn-danger pull-right') do%> 
      <i class="icon-trash icon-white"></i>
    <% end %>
  <% end %>

  <div class="control-group extended-edit">
    <label class="control-label" for="name">
      <%=t :user, scope: [:activerecord, :models, :client]%>
    </label>
    <div class="controls">
      <%= collection_select(:client, :user_id, User.all, :id, :name) %>
    </div>
  </div>

  <div class="control-group ">
    <label class="control-label" for="client_name">
      <%=t :name, scope: [:activerecord, :models, :client]%>
    </label>
    <div class="controls">
      <%= f.text_field(:name, class: "input-xxlarge disabled", disabled: :disabled) %>
      <div style="display: inline-block">
        <a href="#" class="btn form-edit-link"><i class="icon-edit"></i></a>
      </div>
    </div>
  </div>

  <div class="control-group extended-edit">
    <label class="control-label" for="client_local_name">
      <%=t :local_name, scope: [:activerecord, :models, :client]%>
    </label>
    <div class="controls">
      <%= f.text_field(:local_name, class: "input-xxlarge") %>
    </div>
  </div>

  <div class="control-group extended-edit">
    <label class="control-label" for="contacts">
      <%=t :contacts, scope: [:activerecord, :models, :client]%>
      <span class="btn" id="add_contact"><i class="icon-plus"></i></span>
    </label>
    <div class="controls">
      <div id="contacts">
        <%= render @client.contacts %>
      </div>
    </div>
  </div>
  <div class="control-group extended-edit">
    <label class="control-label" for="billing_addresses">
      <%=t :billing_addresses, scope: [:activerecord, :models, :client]%>
      <span class="btn" id="add_billing_address"><i class="icon-plus"></i></span>
    </label>
    <div class="controls">
      <div id="billing_addresses">
        <%= render @client.billing_addresses %>
      </div>
    </div>
  </div>

  <div class="control-group extended-edit">
    <label class="control-label" for="accounting_code">
      <%=t :accounting_code, scope: [:activerecord, :models, :client]%>
    </label>
    <div class="controls">
      <%= f.text_field(:accounting_code, class: 'input-small')%>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label" for="memo">
      <%=t :memo, scope: [:activerecord, :models, :memo]%>
    </label>
    <div class="controls">
      <%= f.text_area(:memo, :rows => 10, class: "input-xxlarge disabled", disabled: :disabled) %>
    </div>
  </div>

  <div class="form-actions extended-edit">
    <button type="submit" id="save_client" class="btn"><%=t :save%></button>
  </div>

<% end %>
  <%= render 'add_contact' %>
  <%= render 'contacts/contact', contact: Contact.new, hidden: true %>
  <%= render 'add_billing_address' %>
  <%= render 'billing_addresses/billing_address', billing_address: BillingAddress.new, hidden: true %>
<%= javascript_include_tag "clients" %>
  <script type="text/javascript">
    // TODO git this out of the view and include it when you need it
</script>

app/views/clients/index.html.erb
    <%= render 'layouts/search_list',  items: @clients, 
      list_label: t(:clients),
      item_label: Proc.new { |item| "#{item.name}(#{item.local_name})" },
      default_label: I18n.t(:only_my_items),
      alternate_label: I18n.t(:all_items),
      alternate_path: clients_path(alternate: 1) %>

    <%= render 'layouts/index', title: I18n.t(:clients), 
      intro: I18n.t(:clients_introduction),
      button: I18n.t(:create_client),
      path: new_client_path %> 

app/views/clients/new.html.erb
<%= render 'layouts/search_list',  items: @clients, 
  list_label: t(:clients),
  item_label: Proc.new { |item| "#{item.name}(#{item.local_name})" },
  default_label: I18n.t(:only_my_items),
  alternate_label: I18n.t(:all_items),
  alternate_label: I18n.t(:only_my_items),
  alternate_path: new_client_path(@client, alternate: 1) %>


<div class="span9">
  <% flash.each do |name, msg| %>
    <%= content_tag(:div, msg, :id => "flash_#{name}") %>
  <% end %>

  <div class="well">
    <legend><%=t :new_client_legend_html %> </legend>
    <%= render 'form' %>
  </div>
  <script>
    $(document).ready(function() {
      $('.form-edit-link').click();
    })
  </script>
</div>

app/views/clients/show.html.erb
<%= render 'layouts/search_list',  items: @clients, 
  list_label: t(:clients),
  item_label: Proc.new { |item| "#{item.name}(#{item.local_name})" },
  default_label: I18n.t(:only_my_items),
  alternate_label: I18n.t(:all_items),
  alternate_path: client_path(@client, alternate: 1) %>

<div class="span9">

  <% flash.each do |name, msg| %>
    <%= content_tag(:div, msg, :id => "flash_#{name}") %>
  <% end %>
  <div class="btn-toolbar">

    <div class="btn-group">
      <%= link_to(new_work_order_path(client_id: @client.id), class: 'btn') do %>
        <i class="icon-plus"></i> New Work Order
      <% end %>
      <%= link_to(work_orders_path(client_id: @client.id), class: 'btn') do %>
        <i class="icon-bar-chart"></i> Show Work Orders
      <% end %>
    </div>
    <div class="btn-group">

      <%= link_to(new_work_order_path(client_id: @client.id), class: 'btn') do %>
        <i class="icon-bar-chart"></i> Sales Report
      <% end %>

    </div>
  </div>
  <div class="well">
    <%= render 'form' %>
  </div>
</div>