config/routes.rb
Rekk::Application.routes.draw do

  resources :work_orders, except: [:edit]
  resources :comments
  resources :billing_addresses, only: [:create]
  resources :home, only: [:index]
  resources :users, only: [:index, :show, :destroy]
  resources :clients
  resources :products do
    collection do
      get :picker
    end
  end
  resources :product_types, except: [:destroy, :edit]
  resources :roles
  resources :contacts, only: [:index, :show]
  resources :work_order_products
  get '/login', to: 'home#login', as: :login
  get   '/logout', to: 'sessions#logout'

  match '/auth/:provider/callback', to: 'sessions#create'
  match '/auth/failure', to: 'sessions#failure' 

  root :to => 'home#index'

end

app/models/work_order.rb
class WorkOrder < ActiveRecord::Base
  belongs_to :author, class_name: 'User', inverse_of: :authored_work_orders
  belongs_to :owner, class_name: 'User', inverse_of: :owned_work_orders
  belongs_to :client, inverse_of: :work_orders
  belongs_to :payment, inverse_of: :work_order, dependent: :delete

  has_many :work_order_products, dependent: :delete_all, inverse_of: :work_order
  has_one :billing_address, through: :payment

  attr_accessible :author_id, :owner_id, :client_id, :payment_type_id,
                  :memo, :work_order_products_attributes, :payment_attributes, :user_pays

  accepts_nested_attributes_for :work_order_products, allow_destroy: true
  accepts_nested_attributes_for :payment

  validates_presence_of :client_id, :owner_id, :author_id
  validates_associated :payment

  default_scope order('created_at desc')

  acts_as_commentable

  paginates_per 2

  def user_pays
    self.payment_id.nil? unless new_record?
  end

  def user_pays=(is_user_pays)
    if is_user_pays === 'true' && payment
      payment.destroy
      self.payment = nil
    end
  end

  def self.search(params)
    scoped= WorkOrder
    if params[:client_id].present?
      scoped = scoped.where(client_id: params[:client_id])
    end
    if params[:owner_id].present?
      scoped = scoped.where(owner_id: params[:owner_id])
    end
    scoped
  end

  def self.by_author(user)
    where(author_id: user.id)
  end

  def self.by_owner(user)
    where owner_id: user.id
  end

  def self.by_client(client)
    where client_id: client.id
  end

  def self.by_status(status)
    where status: status
  end
 end

app/controllers/work_orders_controller.rb
class WorkOrdersController < ApplicationController
  protect_from_forgery
  before_filter :work_orders_list, only: [:index]
  # GET /work_orders
  # GET /work_orders.json
  def index
    # how to deal with search, selfish and status params?
    @clients = Client.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @work_orders }
    end
  end

  # GET /work_orders/1
  # GET /work_orders/1.json
  def show
    @work_order = WorkOrder.find(params[:id], include: :payment)
    # This feels wrong - the payment object must be created or we cannot render the nested form
    @work_order.payment ||= Payment.new
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @work_order }
    end
  end

  # GET /work_orders/new
  # GET /work_orders/new.json
  def new
    @work_order = WorkOrder.new
    @work_order.author = current_user
    @work_order.payment ||= Payment.new
    @work_order.client = Client.find(params[:client_id]) if params[:client_id]
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @work_order }
    end
  end

  # POST /work_orders
  # POST /work_orders.json
  def create
    @work_order = WorkOrder.new(params[:work_order])

    respond_to do |format|
      if @work_order.save
        format.html { redirect_to @work_order, notice: 'Work order was successfully created.' }
        format.json { render json: @work_order, status: :created, location: @work_order }
      else
        format.html { render action: "new" }
        format.json { render json: @work_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /work_orders/1
  # PUT /work_orders/1.json
  def update
    @work_order = WorkOrder.find(params[:id])

    respond_to do |format|
      puts params[:work_order]
      if @work_order.update_attributes(params[:work_order])
        format.html { redirect_to @work_order, notice: 'Work order was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "show" }
        format.json { render json: @work_order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /work_orders/1
  # DELETE /work_orders/1.json
  def destroy
    @work_order = WorkOrder.find(params[:id])
    @work_order.destroy

    respond_to do |format|
      format.html { redirect_to work_orders_url }
      format.json { head :no_content }
    end
  end
  private
  def work_orders_list
    params[:owner_id] = current_user.id if params[:selfish] == "true"
    puts params
    @work_orders = WorkOrder.search(params).page(params[:page])
  end
end

app/helpers/work_orders_helper.rb
module WorkOrdersHelper
end

app/views/work_orders/_form.html.erb
<%= form_for(@work_order, html: { class: 'form-inline' }) do |f| %>
  <%= f.hidden_field :id, value: @work_order.id %>
  <div class='row-fluid'> 

    <div class="span3">
      <label for="client">
        <%= t :client, scope: [:activerecord, :models, :work_order] %>

      </label>
      <%= f.hidden_field :client_id, value: @work_order.client.id %>
      <input type="text" class="" value="<%= @work_order.client.local_name %>" readonly></input>
    </div>

    <div class="span3">
      <label for="owner">
        <%= t :owner, scope: [:activerecord, :models, :work_order] %>
      </label>
      <%= collection_select(:work_order, :owner_id, User.all, :id, :name) %>
    </div>

    <div class="span3">

      <label for="author">
        <%= t :author, scope: [:activerecord, :models, :work_order] %>
      </label>
      <%= collection_select(:work_order, :author_id, User.all, :id, :name, html: { disabled: :disabled }) %>
    </div>


    <div class="span3">
      <div class="pull-right">
        <label for="created">
          <%= t :created, scope: [:activerecord, :models, :work_order] %>
        </label>
        <input type="text" class="" value="<%= @work_order.created_at || Time.now.strftime('%Y-%m-%d %H:%M') %>" readonly></input>
      </div>

    </div>
  </div>
  <!--
  <div class="span2">
    <label for="updated">
      <%= t :updated, scope: [:activerecord, :models, :work_order] %>
    </label>
    <input type="text" class="input-medium" value="<%= @work_order.updated_at || Time.now.strftime('%Y-%m-%d %H:%M') %>" readonly></input>
  </div> 
  -->
  <br>

  <div class="row-fluid">
    <div class="span12">
      <ul class="nav nav-tabs" style="margin-bottom: 0px">
        <li class="active"><a href="#work_order_products_pane" data-toggle="tab">Products</a></li>
        <li><a href="#memo" data-toggle="tab">Memo</a></li>
        <li><a href="#payment_info" data-toggle="tab">Payment</a></li>
        <li><a href="#client_memo" data-toggle="tab">Client Memo</a></li>
        <li><a href="#work_order_change_log" data-toggle="tab">Change Log</a></li>
      </ul>

      <div class="tab-content">

        <!-- Work Order Products -->
        <div id="work_order_products_pane" class="tab-pane active">
          <div class="btn-toolbar">
            <div class="btn-group">
              <%= link_to 'add', new_work_order_product_path(work_order_id: @work_order.id), remote: true, class: 'btn add-work-order-product' %>
              <%= link_to 'peruse', work_order_products_path(work_order_id: @work_order.id), class: 'btn', target: '_blank' %>
            </div>
          </div>
          <table class="table table-hover table-bordered" id="work_order_products">

            <thead>
              <th></th>
              <th class="product_name"><%= t :product %></th>
              <th class="count"><%= t :count %></th>
              <th class="fee"><%= t :fee %></th>
              <th class="schedule"><%= t :schedule %></th>
              <th class="memo"><%= t :memo %></th>
            </thead>
            <tbody>
            <% @work_order.work_order_products.each do |product| %> 
              <%= render 'work_order_products/li', work_order_product: product %>
            <% end%>
          </tbody>
          </table>
        </div>

        <!-- Memo -->
        <div class="tab-pane" id="memo">
          <%= f.text_area(:memo, rows: 6, class: "span12") %>
        </div>

        <!-- Payment -->
       <div class="tab-pane" id="payment_info">

         <!-- TODO - 
         When the status of the service request is invoiced, shipping or closed - these fields need
         to be disabled with the exception of paid on.
         -->
          <% if @work_order.payment.paid_on %>
            <label class="control-label">
              <div>PAID:<%= @work_order.payment.paid_on %></div>
            </label>
          <% else %>
            <label class="control-label" for="payment_type">
              <%= t :payment_type, scope: [:activerecord, :models, :work_order] %>
            </label>

            <div class="controls"> 
              <label class="radio inline">
                <%= f.radio_button :user_pays, false, :checked => !@work_order.user_pays %> 
                <span class="icon-envelope-alt icon-large"> <%= t(:invoice, scope: [:views, :work_order, :payment_types]) %></span>
              </label>
              <label class="radio inline">
                <%= f.radio_button :user_pays, true,  :checked => @work_order.user_pays %>
                <span class="icon-user icon-large"> <%= t(:user, scope: [:views, :work_order, :payment_types]) %></span>
              </label>
            </div>
            <br/>
            <%= render 'payments/form', form: f %>          
          <% end %>
        </div>

        <!-- Client Memo -->
         <div class="tab-pane" id="client_memo">
          <textarea class="span12" rows="6" id="client_memo" readonly><%= @work_order.client ? @work_order.client.memo : '' %></textarea>
        </div>

        <!-- Change Log -->
        <div id="work_order_change_log" class="tab-pane">
          <div class="btn-toolbar">
            <div class="btn-group">
              <%= link_to 'add', new_comment_path(commentable_id: @work_order.id, type: @work_order.class), remote: true, class: 'btn add-comment' %>
              <%= link_to 'peruse', comments_path(commentable_id: @work_order.id, type: @work_order.class), class: 'btn', target: '_blank' %>
            </div>
          </div>
          <ul id="comments">
            <% @work_order.comments.each do |comment| %>
              <%= render 'comments/li', comment: comment %>
            <% end %>
          </ul>
        </div>
   


      </div>
    </div> 

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%= javascript_include_tag "work_orders" %>

<script type="text/javascript">
  //  $('#payment_tabs a:first').tab('show')
</script>
<%= render 'clients/add_billing_address' %>

app/views/work_orders/_search.html.erb
<div class="span2">
  <div class="well">
   <h6 class=""> Find a Work Order </h6>
       <br>
    <ul class="nav nav-list">
      <li class="nav-header">
      <%= t(:by_status) %>
      </li>
      <li class="<%= 'active' if params[:status] == 'new' %>">
      <%= link_to(work_orders_path(params: request.query_parameters.merge({status: 'new'}))) do %>
        <i class="icon-plus-sign"></i>
        <%= t :new %>
      <% end %>
      </li>
      <li class="<%= 'active' if params[:status] == 'submitted' %>"> 
      <%= link_to(work_orders_path(params: request.query_parameters.merge({status: 'submitted'}))) do %>
        <i class="icon-upload-alt"></i>
        <%= t :submitted %>
      <% end %>
      </li>
      <li class="<%= 'active' if params[:status] == 'processed' %>"> 
      <%= link_to(work_orders_path(params: request.query_parameters.merge({status: 'processed'}))) do %>
        <i class="icon-bolt"></i>
        <%= t :processed %>
      <% end %>
      </li>
      <li class="<%= 'active' if params[:status] == 'invoiced' %>"> 
      <%= link_to(work_orders_path(params: request.query_parameters.merge({status: 'invoiced'}))) do %>
        <i class="icon-download-alt"></i>
        <%= t :invoiced %>
      <% end %>
      </li>

      <li class="<%= 'active' if params[:status] == 'shipping' %>"> 

      <%= link_to(work_orders_path(params: request.query_parameters.merge({status: 'shipping'}))) do %>
        <i class="icon-envelope-alt"></i>
        <%= t :shipping %>
      <% end %>
      </li>




    </ul>
  </div>
</div>

app/views/work_orders/edit.html.erb
<h1>Editing work_order</h1>

<%= render 'form' %>

<%= link_to 'Back', work_orders_path %>

app/views/work_orders/index.html.erb
<%= render 'search' %>
<div class="span10">
  <div class="btn-toolbar">
    <div class="btn-group">
      <div class="btn input-prepend">
        <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
          <i class="icon-check-empty icon-large">&nbsp;&nbsp;<span class="icon-caret-down"></span></i>
        </a>
        <ul class="dropdown-menu">
          <li><a href="#"><i class="icon-check"> All</i></a></li>
          <li><a href="#"><i class="icon-check-empty"> None</i></a></li>
        </ul>

        <span class="add-on"><i class="icon-search icon-large"></i></span>
        <input class="input-xxlarge" type="text" placeholder="<%= I18n.t(:search)%>"/>
        <%= link_to work_orders_path do %>
          <li class="btn btn-info" id="search"><i class="icon-refresh"></i></li>
        <% end %>
          <%= link_to t(:only_me), work_orders_path(params: request.query_parameters.merge({selfish:params[:selfish] != 'true'})), class: "btn #{'active' if params[:selfish] == 'true'}" %>
        <a style="margin-left:20px;" class="btn btn-danger"><i class="icon-trash icon-white"> Delete</i></a>
      </div>
    </div>
  </div>
  <%= paginate @work_orders %>
  <% @work_orders.each do |work_order| %>
    <a href="<%= work_order_path(work_order) %>">
      <div class="row well span12" style="margin-left:0px;">
        <div class="span1 item-selector">
          <input type="checkbox" name="work_order_<%=work_order.id%>"/>
        </div>
        <div class="span11">
          <div class="span9">
            <h3><%= work_order.client.name %></h3>
            <h6><small><%= t :owner, scope: [:activerecord, :models, :work_order]%>:</small>
              <%= work_order.owner.name %></h6>
            <h6><small><%= t :author, scope: [:activerecord, :models, :work_order]%>:</small>
              <%= work_order.author.name %></h6>
          </div>

          <div class="span3">
            <label class="pull-right" style="text-align:right">

              <h2>&yen;300,000,000</h2>
              <h6><small>
              <%= t :payment_deadline, scope: [:activerecord, :models, :payment] %>
            </small>
              <%= work_order.payment.payment_deadline if work_order.payment%>
            </h6>
              <h6><%= work_order.status %></h6>
            </label>
          </div>
        </div>
      </a>
        <div class="span11">
          <br>
          <div class="tabbable tabs-left">
            <ul class="nav nav-tabs" id="work_order_tabs">
              <li class="active"><a href="#products_<%= work_order.id %>" data-toggle="tab"><%= t :products %></a></li>
              <li><a href="#memo_<%= work_order.id %>" data-toggle="tab"><%= t :memo %></a></li>
              <li><a href="#change_log_<%= work_order.id %>" data-toggle="tab"><%= t :change_log %></a></li>
            </ul>
            <div class="tab-content">
              <div class="tab-pane active scrollable" id="products_<%= work_order.id %>">
                foo
                <br>
                foo
                <br>
                foo
                <br>
                foo
                <br>
                foo
                <br>
                foo
                <br>
                foo
                <br>
                foo
                <br>
                foo
                <br>
                foo
                <br>
                foo
                <br>
                foo
                <br>
                foo
                <br>
              </div>
              <div class="tab-pane" id="memo_<%= work_order.id %>">
                <%= work_order.memo %>
              </div>
              <div class="tab-pane" id="change_log_<%= work_order.id %>">
                hoge
              </div>
            </div>
          </div>
        </div>
      </div>
  <% end %>
  <%= paginate @work_orders %>
</div>
<br><br>

app/views/work_orders/new.html.erb
 <div class="span12">
  <% if @work_order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@work_order.errors.count, "error") %> prohibited this work_order from being saved:</h2>

      <ul>
        <% @work_order.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 <div class="well">
    <%= render 'form' %>
  </div>
</div>

app/views/work_orders/show.html.erb
<div class="span122">

  <%= render "shared/error_messages", :target => @work_order %>
  <% flash.each do |name, msg| %>
    <%= content_tag(:div, msg, :id => "flash_#{name}") %>
  <% end %>

  <div class="well">
    <%= render 'form' %>
  </div>
</div>